IPT Unit Tests
InvArch/InvArch-Frames pull request #131
Opened 2022-03-21 04:42 UTC by S0raWasTaken

Add Ipt unit tests
closes #116

2022-03-21 04:45 UTC, S0raWasTaken reviewed
@arrudagates I have an issue with `mock.rs`. It would be a great help if you could look into it

2022-04-04 18:31 UTC, arrudagates reviewed
Looks good, just missing the vote tests now.

2022-04-07 19:51 UTC, arrudagates requested changes

2022-04-07 19:51 UTC, arrudagates commented on INV4/pallet-ipt/src/tests.rs
> +        assert_ok!(Ipt::vote_multisig(Origin::signed(ALICE), 0, call_hash)); // fails: NotEnoughAmount
```suggestion
        //  assert_ok!(Ipt::vote_multisig(Origin::signed(ALICE), 0, call_hash)); // fails: NotEnoughAmount
```
Let's track this in a separate issue, but for now we will force the tests to pass, so they don't block other ongoing tasks

2022-04-07 20:01 UTC, arrudagates commented on INV4/pallet-ipt/src/tests.rs
> +        assert_eq!(Balance::<Runtime>::get(0, BOB), Some(1000));
```suggestion
        // assert_eq!(Multisig::<Runtime>::get((0, call_hash)), None);
        // assert_eq!(Balance::<Runtime>::get(0, BOB), Some(1000));
```

2022-04-07 20:06 UTC, merged